<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyName>WhistleWindLobotomyMod</AssemblyName>
		<Description>A mod for Inscryption adding cards and sigils based on the abnormalities from Lobotomy Corporation and Library of Ruina.</Description>
		<Version>3.0.0</Version>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DebugType>full</DebugType>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Artwork\*.png" />
	</ItemGroup>
  
	<ItemGroup>
		<EmbeddedResource Include="Artwork\*.png" />
	</ItemGroup>
  
	<ItemGroup>
		<None Remove="lobmodassets" />
		<None Remove="lobmodmusic" />
	</ItemGroup>
  
	<ItemGroup>
		<EmbeddedResource Include="lobmodassets" />
		<EmbeddedResource Include="lobmodmusic" />
	</ItemGroup>
  
	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" GeneratePathProperty="true" />
		<PackageReference Include="BepInEx.Core" Version="5.4.19" GeneratePathProperty="true" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" GeneratePathProperty="true" />
		<PackageReference Include="UnityEngine.Modules" Version="2019.4.24" GeneratePathProperty="true" IncludeAssets="compile" />
		<PackageReference Include="Inscryption.GameLibs" Version="1.9.0-r.0" />
	</ItemGroup>
  
	<ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="InscryptionAPI" Private="false">
			<HintPath>..\lib\InscryptionAPI.dll</HintPath>
		</Reference>
		<Reference Include="InscryptionCommunityPatch" Private="false">
			<HintPath>..\lib\InscryptionCommunityPatch.dll</HintPath>
		</Reference>
		<Reference Include="Infiniscryption.Spells" Private="false">
			<HintPath>..\lib\Infiniscryption.Spells.dll</HintPath>
		</Reference>
		<Reference Include="Infiniscryption.PackManager" Private="false">
			<HintPath>..\lib\Infiniscryption.PackManager.dll</HintPath>
		</Reference>
		<Reference Include="Infiniscryption.Achievements" Private="false">
			<HintPath>..\lib\Infiniscryption.Achievements.dll</HintPath>
		</Reference>
		<Reference Include="WhistleWind.AbnormalSigils" Private="false">
			<HintPath>..\Compiled\WhistleWind.AbnormalSigils.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy /Y $(TargetDir)\$(AssemblyName).dll ..\Compiled\$(ProjectName).dll" />
		<Copy Condition="Exists('C:\Program Files (x86)\Steam\steamapps\common\Inscryption\')" SourceFiles="$(TargetDir)\$(AssemblyName).dll" DestinationFolder="C:\Program Files (x86)\Steam\steamapps\common\Inscryption\BepInEx\plugins\" />
	</Target>
</Project>