//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhistleWindLobotomyMod.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhistleWindLobotomyMod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] allAroundHelper {
            get {
                object obj = ResourceManager.GetObject("allAroundHelper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] allAroundHelper_emission {
            get {
                object obj = ResourceManager.GetObject("allAroundHelper_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] alriune {
            get {
                object obj = ResourceManager.GetObject("alriune", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] alriune_emission {
            get {
                object obj = ResourceManager.GetObject("alriune_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleHeretic {
            get {
                object obj = ResourceManager.GetObject("apostleHeretic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleHeretic_emission {
            get {
                object obj = ResourceManager.GetObject("apostleHeretic_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleScythe {
            get {
                object obj = ResourceManager.GetObject("apostleScythe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleScythe_emission {
            get {
                object obj = ResourceManager.GetObject("apostleScythe_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleScytheDown {
            get {
                object obj = ResourceManager.GetObject("apostleScytheDown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleScytheDown_emission {
            get {
                object obj = ResourceManager.GetObject("apostleScytheDown_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleSpear {
            get {
                object obj = ResourceManager.GetObject("apostleSpear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleSpear_emission {
            get {
                object obj = ResourceManager.GetObject("apostleSpear_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleSpearDown {
            get {
                object obj = ResourceManager.GetObject("apostleSpearDown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleSpearDown_emission {
            get {
                object obj = ResourceManager.GetObject("apostleSpearDown_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleStaff {
            get {
                object obj = ResourceManager.GetObject("apostleStaff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleStaff_emission {
            get {
                object obj = ResourceManager.GetObject("apostleStaff_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleStaffDown {
            get {
                object obj = ResourceManager.GetObject("apostleStaffDown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] apostleStaffDown_emission {
            get {
                object obj = ResourceManager.GetObject("apostleStaffDown_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] armyInBlack {
            get {
                object obj = ResourceManager.GetObject("armyInBlack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] armyInBlack_emission {
            get {
                object obj = ResourceManager.GetObject("armyInBlack_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] armyInPink {
            get {
                object obj = ResourceManager.GetObject("armyInPink", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] armyInPink_emission {
            get {
                object obj = ResourceManager.GetObject("armyInPink_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] beautyAndBeast {
            get {
                object obj = ResourceManager.GetObject("beautyAndBeast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] beautyAndBeast_emission {
            get {
                object obj = ResourceManager.GetObject("beautyAndBeast_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bigBird {
            get {
                object obj = ResourceManager.GetObject("bigBird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bigBird_emission {
            get {
                object obj = ResourceManager.GetObject("bigBird_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bloodBath {
            get {
                object obj = ResourceManager.GetObject("bloodBath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bloodBath_emission {
            get {
                object obj = ResourceManager.GetObject("bloodBath_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bloodBath1 {
            get {
                object obj = ResourceManager.GetObject("bloodBath1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bloodBath1_emission {
            get {
                object obj = ResourceManager.GetObject("bloodBath1_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bloodBath2 {
            get {
                object obj = ResourceManager.GetObject("bloodBath2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bloodBath2_emission {
            get {
                object obj = ResourceManager.GetObject("bloodBath2_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bloodBath3 {
            get {
                object obj = ResourceManager.GetObject("bloodBath3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bloodBath3_emission {
            get {
                object obj = ResourceManager.GetObject("bloodBath3_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] blueStar {
            get {
                object obj = ResourceManager.GetObject("blueStar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] blueStar_emission {
            get {
                object obj = ResourceManager.GetObject("blueStar_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] blueStar2 {
            get {
                object obj = ResourceManager.GetObject("blueStar2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] blueStar2_emission {
            get {
                object obj = ResourceManager.GetObject("blueStar2_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] blueStar3 {
            get {
                object obj = ResourceManager.GetObject("blueStar3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] blueStar3_emission {
            get {
                object obj = ResourceManager.GetObject("blueStar3_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] burrowingHeaven {
            get {
                object obj = ResourceManager.GetObject("burrowingHeaven", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] burrowingHeaven_emission {
            get {
                object obj = ResourceManager.GetObject("burrowingHeaven_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] canOfWellCheers {
            get {
                object obj = ResourceManager.GetObject("canOfWellCheers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] canOfWellCheers_emission {
            get {
                object obj = ResourceManager.GetObject("canOfWellCheers_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] censored {
            get {
                object obj = ResourceManager.GetObject("censored", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] censored_emission {
            get {
                object obj = ResourceManager.GetObject("censored_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] censored_title {
            get {
                object obj = ResourceManager.GetObject("censored_title", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] censoredMinion {
            get {
                object obj = ResourceManager.GetObject("censoredMinion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] censoredMinion_emission {
            get {
                object obj = ResourceManager.GetObject("censoredMinion_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] cloudedMonk {
            get {
                object obj = ResourceManager.GetObject("cloudedMonk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] crumblingArmour {
            get {
                object obj = ResourceManager.GetObject("crumblingArmour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] derFreischutz {
            get {
                object obj = ResourceManager.GetObject("derFreischutz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dimensionalRefraction {
            get {
                object obj = ResourceManager.GetObject("dimensionalRefraction", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dimensionalRefraction_emission {
            get {
                object obj = ResourceManager.GetObject("dimensionalRefraction_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dontTouchMe {
            get {
                object obj = ResourceManager.GetObject("dontTouchMe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dontTouchMe_emission {
            get {
                object obj = ResourceManager.GetObject("dontTouchMe_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dreamingCurrent {
            get {
                object obj = ResourceManager.GetObject("dreamingCurrent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] expressHellTrain {
            get {
                object obj = ResourceManager.GetObject("expressHellTrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] expressHellTrain_emission {
            get {
                object obj = ResourceManager.GetObject("expressHellTrain_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fairyFestival {
            get {
                object obj = ResourceManager.GetObject("fairyFestival", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fleshIdol {
            get {
                object obj = ResourceManager.GetObject("fleshIdol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] forsakenMurderer {
            get {
                object obj = ResourceManager.GetObject("forsakenMurderer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] forsakenMurderer_emission {
            get {
                object obj = ResourceManager.GetObject("forsakenMurderer_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] funeralOfButterflies {
            get {
                object obj = ResourceManager.GetObject("funeralOfButterflies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] graveOfBlossoms {
            get {
                object obj = ResourceManager.GetObject("graveOfBlossoms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] graveOfBlossoms_emission {
            get {
                object obj = ResourceManager.GetObject("graveOfBlossoms_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] happyTeddyBear {
            get {
                object obj = ResourceManager.GetObject("happyTeddyBear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] heartOfAspiration {
            get {
                object obj = ResourceManager.GetObject("heartOfAspiration", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] honouredMonk {
            get {
                object obj = ResourceManager.GetObject("honouredMonk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hundredsGoodDeeds {
            get {
                object obj = ResourceManager.GetObject("hundredsGoodDeeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] judgementBird {
            get {
                object obj = ResourceManager.GetObject("judgementBird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] kingOfGreed {
            get {
                object obj = ResourceManager.GetObject("kingOfGreed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] knightOfDespair {
            get {
                object obj = ResourceManager.GetObject("knightOfDespair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] laetitia {
            get {
                object obj = ResourceManager.GetObject("laetitia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] laetitiaFriend {
            get {
                object obj = ResourceManager.GetObject("laetitiaFriend", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] luminousBracelet {
            get {
                object obj = ResourceManager.GetObject("luminousBracelet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] magicalGirlDiamond {
            get {
                object obj = ResourceManager.GetObject("magicalGirlDiamond", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] magicalGirlHeart {
            get {
                object obj = ResourceManager.GetObject("magicalGirlHeart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] magicalGirlSpade {
            get {
                object obj = ResourceManager.GetObject("magicalGirlSpade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] meatLantern {
            get {
                object obj = ResourceManager.GetObject("meatLantern", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] meatLantern_emission {
            get {
                object obj = ResourceManager.GetObject("meatLantern_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] meltingLove {
            get {
                object obj = ResourceManager.GetObject("meltingLove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] meltingLoveMinion {
            get {
                object obj = ResourceManager.GetObject("meltingLoveMinion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] meltingLoveMinion_emission {
            get {
                object obj = ResourceManager.GetObject("meltingLoveMinion_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mhz176 {
            get {
                object obj = ResourceManager.GetObject("mhz176", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mhz176_emission {
            get {
                object obj = ResourceManager.GetObject("mhz176_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mirrorOfAdjustment {
            get {
                object obj = ResourceManager.GetObject("mirrorOfAdjustment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mountainOfBodies {
            get {
                object obj = ResourceManager.GetObject("mountainOfBodies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mountainOfBodies2 {
            get {
                object obj = ResourceManager.GetObject("mountainOfBodies2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mountainOfBodies3 {
            get {
                object obj = ResourceManager.GetObject("mountainOfBodies3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] namelessFetus {
            get {
                object obj = ResourceManager.GetObject("namelessFetus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] namelessFetus_emission {
            get {
                object obj = ResourceManager.GetObject("namelessFetus_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] namelessFetusAwake {
            get {
                object obj = ResourceManager.GetObject("namelessFetusAwake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] namelessFetusAwake_emission {
            get {
                object obj = ResourceManager.GetObject("namelessFetusAwake_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] notesFromResearcher {
            get {
                object obj = ResourceManager.GetObject("notesFromResearcher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] nothingThere {
            get {
                object obj = ResourceManager.GetObject("nothingThere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] nothingThere_emission {
            get {
                object obj = ResourceManager.GetObject("nothingThere_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] nothingThereEgg {
            get {
                object obj = ResourceManager.GetObject("nothingThereEgg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] nothingThereEgg_emission {
            get {
                object obj = ResourceManager.GetObject("nothingThereEgg_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] nothingThereFinal {
            get {
                object obj = ResourceManager.GetObject("nothingThereFinal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] nothingThereTrue {
            get {
                object obj = ResourceManager.GetObject("nothingThereTrue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oldLady {
            get {
                object obj = ResourceManager.GetObject("oldLady", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oneSin {
            get {
                object obj = ResourceManager.GetObject("oneSin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] parasiteTree {
            get {
                object obj = ResourceManager.GetObject("parasiteTree", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] parasiteTreeSapling {
            get {
                object obj = ResourceManager.GetObject("parasiteTreeSapling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] plagueDoctor {
            get {
                object obj = ResourceManager.GetObject("plagueDoctor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] porccubus {
            get {
                object obj = ResourceManager.GetObject("porccubus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ppodae {
            get {
                object obj = ResourceManager.GetObject("ppodae", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ppodae_emission {
            get {
                object obj = ResourceManager.GetObject("ppodae_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ppodaeBuff {
            get {
                object obj = ResourceManager.GetObject("ppodaeBuff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ppodaeBuff_emission {
            get {
                object obj = ResourceManager.GetObject("ppodaeBuff_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] punishingBird {
            get {
                object obj = ResourceManager.GetObject("punishingBird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] punishingBird_emission {
            get {
                object obj = ResourceManager.GetObject("punishingBird_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] queenBee {
            get {
                object obj = ResourceManager.GetObject("queenBee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] queenBee_emission {
            get {
                object obj = ResourceManager.GetObject("queenBee_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] queenBeeWorker {
            get {
                object obj = ResourceManager.GetObject("queenBeeWorker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] queenBeeWorker_emission {
            get {
                object obj = ResourceManager.GetObject("queenBeeWorker_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] queenOfHatred {
            get {
                object obj = ResourceManager.GetObject("queenOfHatred", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] queenOfHatredExhausted {
            get {
                object obj = ResourceManager.GetObject("queenOfHatredExhausted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] redHoodedMercenary {
            get {
                object obj = ResourceManager.GetObject("redHoodedMercenary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] redShoes {
            get {
                object obj = ResourceManager.GetObject("redShoes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] redShoes_emission {
            get {
                object obj = ResourceManager.GetObject("redShoes_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] rudoltaSleigh {
            get {
                object obj = ResourceManager.GetObject("rudoltaSleigh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] rudoltaSleigh_emission {
            get {
                object obj = ResourceManager.GetObject("rudoltaSleigh_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] schadenfreude {
            get {
                object obj = ResourceManager.GetObject("schadenfreude", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] scorchedGirl {
            get {
                object obj = ResourceManager.GetObject("scorchedGirl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] scorchedGirl_emission {
            get {
                object obj = ResourceManager.GetObject("scorchedGirl_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] shelterFrom27March {
            get {
                object obj = ResourceManager.GetObject("shelterFrom27March", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] shelterFrom27March_emission {
            get {
                object obj = ResourceManager.GetObject("shelterFrom27March_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilAggravating {
            get {
                object obj = ResourceManager.GetObject("sigilAggravating", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilApostle {
            get {
                object obj = ResourceManager.GetObject("sigilApostle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilAssimilator {
            get {
                object obj = ResourceManager.GetObject("sigilAssimilator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilBitterEnemies {
            get {
                object obj = ResourceManager.GetObject("sigilBitterEnemies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilBloodfiend {
            get {
                object obj = ResourceManager.GetObject("sigilBloodfiend", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilBroodMother {
            get {
                object obj = ResourceManager.GetObject("sigilBroodMother", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilBurning {
            get {
                object obj = ResourceManager.GetObject("sigilBurning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilConductor {
            get {
                object obj = ResourceManager.GetObject("sigilConductor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilConfession {
            get {
                object obj = ResourceManager.GetObject("sigilConfession", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilCourageous {
            get {
                object obj = ResourceManager.GetObject("sigilCourageous", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilCursed {
            get {
                object obj = ResourceManager.GetObject("sigilCursed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilFlagBearer {
            get {
                object obj = ResourceManager.GetObject("sigilFlagBearer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilFrostRuler {
            get {
                object obj = ResourceManager.GetObject("sigilFrostRuler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilFrozenHeart {
            get {
                object obj = ResourceManager.GetObject("sigilFrozenHeart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilGardener {
            get {
                object obj = ResourceManager.GetObject("sigilGardener", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilGiftGiver {
            get {
                object obj = ResourceManager.GetObject("sigilGiftGiver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilGrinder {
            get {
                object obj = ResourceManager.GetObject("sigilGrinder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilGroupHealer {
            get {
                object obj = ResourceManager.GetObject("sigilGroupHealer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilHealer {
            get {
                object obj = ResourceManager.GetObject("sigilHealer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilHunter {
            get {
                object obj = ResourceManager.GetObject("sigilHunter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilIdol {
            get {
                object obj = ResourceManager.GetObject("sigilIdol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilIrritating {
            get {
                object obj = ResourceManager.GetObject("sigilIrritating", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilMartyr {
            get {
                object obj = ResourceManager.GetObject("sigilMartyr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilPiercing {
            get {
                object obj = ResourceManager.GetObject("sigilPiercing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilProtector {
            get {
                object obj = ResourceManager.GetObject("sigilProtector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilPunisher {
            get {
                object obj = ResourceManager.GetObject("sigilPunisher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilQueenNest {
            get {
                object obj = ResourceManager.GetObject("sigilQueenNest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilQuickDraw {
            get {
                object obj = ResourceManager.GetObject("sigilQuickDraw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilReflector {
            get {
                object obj = ResourceManager.GetObject("sigilReflector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilRegenerator {
            get {
                object obj = ResourceManager.GetObject("sigilRegenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilRoots {
            get {
                object obj = ResourceManager.GetObject("sigilRoots", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilScrambler {
            get {
                object obj = ResourceManager.GetObject("sigilScrambler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilSerpentsNest {
            get {
                object obj = ResourceManager.GetObject("sigilSerpentsNest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilSlime {
            get {
                object obj = ResourceManager.GetObject("sigilSlime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilTeamLeader {
            get {
                object obj = ResourceManager.GetObject("sigilTeamLeader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilTheTrain {
            get {
                object obj = ResourceManager.GetObject("sigilTheTrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilTrueSaviour {
            get {
                object obj = ResourceManager.GetObject("sigilTrueSaviour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilVolatile {
            get {
                object obj = ResourceManager.GetObject("sigilVolatile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sigilWoodcutter {
            get {
                object obj = ResourceManager.GetObject("sigilWoodcutter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] silentEnsemble {
            get {
                object obj = ResourceManager.GetObject("silentEnsemble", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] silentOrchestra {
            get {
                object obj = ResourceManager.GetObject("silentOrchestra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] silentOrchestra_emission {
            get {
                object obj = ResourceManager.GetObject("silentOrchestra_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] singingMachine {
            get {
                object obj = ResourceManager.GetObject("singingMachine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] singingMachine_emission {
            get {
                object obj = ResourceManager.GetObject("singingMachine_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] snowQueen {
            get {
                object obj = ResourceManager.GetObject("snowQueen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] snowQueen_emission {
            get {
                object obj = ResourceManager.GetObject("snowQueen_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] snowQueenIceBlock {
            get {
                object obj = ResourceManager.GetObject("snowQueenIceBlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] snowQueenIceHeart {
            get {
                object obj = ResourceManager.GetObject("snowQueenIceHeart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] snowWhitesApple {
            get {
                object obj = ResourceManager.GetObject("snowWhitesApple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] snowWhitesApple_emission {
            get {
                object obj = ResourceManager.GetObject("snowWhitesApple_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] snowWhitesVine {
            get {
                object obj = ResourceManager.GetObject("snowWhitesVine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spiderBrood {
            get {
                object obj = ResourceManager.GetObject("spiderBrood", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spiderBrood_emission {
            get {
                object obj = ResourceManager.GetObject("spiderBrood_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spiderBud {
            get {
                object obj = ResourceManager.GetObject("spiderBud", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spiderBud_emission {
            get {
                object obj = ResourceManager.GetObject("spiderBud_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spiderling {
            get {
                object obj = ResourceManager.GetObject("spiderling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spiderling_emission {
            get {
                object obj = ResourceManager.GetObject("spiderling_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] testingDummy {
            get {
                object obj = ResourceManager.GetObject("testingDummy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] theFirebird {
            get {
                object obj = ResourceManager.GetObject("theFirebird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] theFirebird_emission {
            get {
                object obj = ResourceManager.GetObject("theFirebird_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] theNakedNest {
            get {
                object obj = ResourceManager.GetObject("theNakedNest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] theNakedNest_emission {
            get {
                object obj = ResourceManager.GetObject("theNakedNest_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] theNakedWorm {
            get {
                object obj = ResourceManager.GetObject("theNakedWorm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] theresia {
            get {
                object obj = ResourceManager.GetObject("theresia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] todaysShyLook {
            get {
                object obj = ResourceManager.GetObject("todaysShyLook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] todaysShyLookAngry {
            get {
                object obj = ResourceManager.GetObject("todaysShyLookAngry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] todaysShyLookHappy {
            get {
                object obj = ResourceManager.GetObject("todaysShyLookHappy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trainingDummy {
            get {
                object obj = ResourceManager.GetObject("trainingDummy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trainingDummy_emission {
            get {
                object obj = ResourceManager.GetObject("trainingDummy_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] voidDream {
            get {
                object obj = ResourceManager.GetObject("voidDream", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] voidDreamRooster {
            get {
                object obj = ResourceManager.GetObject("voidDreamRooster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] wallLady {
            get {
                object obj = ResourceManager.GetObject("wallLady", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] warmHeartedWoodsman {
            get {
                object obj = ResourceManager.GetObject("warmHeartedWoodsman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] weCanChangeAnything {
            get {
                object obj = ResourceManager.GetObject("weCanChangeAnything", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] weCanChangeAnything_emission {
            get {
                object obj = ResourceManager.GetObject("weCanChangeAnything_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] whiteNight {
            get {
                object obj = ResourceManager.GetObject("whiteNight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] whiteNight_emission {
            get {
                object obj = ResourceManager.GetObject("whiteNight_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] whiteNight_title {
            get {
                object obj = ResourceManager.GetObject("whiteNight_title", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] willBeBadWolf {
            get {
                object obj = ResourceManager.GetObject("willBeBadWolf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] wisdomScarecrow {
            get {
                object obj = ResourceManager.GetObject("wisdomScarecrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] wisdomScarecrow_emission {
            get {
                object obj = ResourceManager.GetObject("wisdomScarecrow_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] worldPortrait {
            get {
                object obj = ResourceManager.GetObject("worldPortrait", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] youMustBeHappy {
            get {
                object obj = ResourceManager.GetObject("youMustBeHappy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] youreBald {
            get {
                object obj = ResourceManager.GetObject("youreBald", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
