//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhistleWind.AbnormalSigils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Artwork {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Artwork() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhistleWind.AbnormalSigils.Properties.Artwork", typeof(Artwork).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores {
            get {
                object obj = ResourceManager.GetObject("costSpores", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_10 {
            get {
                object obj = ResourceManager.GetObject("costSpores_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_2 {
            get {
                object obj = ResourceManager.GetObject("costSpores_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_3 {
            get {
                object obj = ResourceManager.GetObject("costSpores_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_4 {
            get {
                object obj = ResourceManager.GetObject("costSpores_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_5 {
            get {
                object obj = ResourceManager.GetObject("costSpores_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_6 {
            get {
                object obj = ResourceManager.GetObject("costSpores_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_7 {
            get {
                object obj = ResourceManager.GetObject("costSpores_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_8 {
            get {
                object obj = ResourceManager.GetObject("costSpores_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_9 {
            get {
                object obj = ResourceManager.GetObject("costSpores_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costSpores_pixel {
            get {
                object obj = ResourceManager.GetObject("costSpores_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dreamOfABlackSwanBrother1 {
            get {
                object obj = ResourceManager.GetObject("dreamOfABlackSwanBrother1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dreamOfABlackSwanBrother2 {
            get {
                object obj = ResourceManager.GetObject("dreamOfABlackSwanBrother2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dreamOfABlackSwanBrother3 {
            get {
                object obj = ResourceManager.GetObject("dreamOfABlackSwanBrother3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dreamOfABlackSwanBrother4 {
            get {
                object obj = ResourceManager.GetObject("dreamOfABlackSwanBrother4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dreamOfABlackSwanBrother5 {
            get {
                object obj = ResourceManager.GetObject("dreamOfABlackSwanBrother5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dreamOfABlackSwanBrother6 {
            get {
                object obj = ResourceManager.GetObject("dreamOfABlackSwanBrother6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] laetitiaFriend {
            get {
                object obj = ResourceManager.GetObject("laetitiaFriend", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] laetitiaFriend_emission {
            get {
                object obj = ResourceManager.GetObject("laetitiaFriend_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] meltingLoveMinion {
            get {
                object obj = ResourceManager.GetObject("meltingLoveMinion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] meltingLoveMinion_emission {
            get {
                object obj = ResourceManager.GetObject("meltingLoveMinion_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ozmaPumpkin {
            get {
                object obj = ResourceManager.GetObject("ozmaPumpkin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ozmaPumpkinJack {
            get {
                object obj = ResourceManager.GetObject("ozmaPumpkinJack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ozmaPumpkinJack_emission {
            get {
                object obj = ResourceManager.GetObject("ozmaPumpkinJack_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] parasiteTreeSapling {
            get {
                object obj = ResourceManager.GetObject("parasiteTreeSapling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] parasiteTreeSapling_emission {
            get {
                object obj = ResourceManager.GetObject("parasiteTreeSapling_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] queenBeeWorker {
            get {
                object obj = ResourceManager.GetObject("queenBeeWorker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] queenBeeWorker_emission {
            get {
                object obj = ResourceManager.GetObject("queenBeeWorker_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilAbnormality {
            get {
                object obj = ResourceManager.GetObject("sigilAbnormality", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilAbnormality_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilAbnormality_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilAggravating {
            get {
                object obj = ResourceManager.GetObject("sigilAggravating", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilAggravating_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilAggravating_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilAlchemist {
            get {
                object obj = ResourceManager.GetObject("sigilAlchemist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilAlchemist_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilAlchemist_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilAssimilator {
            get {
                object obj = ResourceManager.GetObject("sigilAssimilator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilAssimilator_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilAssimilator_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBarreler {
            get {
                object obj = ResourceManager.GetObject("sigilBarreler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBarreler_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilBarreler_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBitterEnemies {
            get {
                object obj = ResourceManager.GetObject("sigilBitterEnemies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBitterEnemies_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilBitterEnemies_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBloodfiend {
            get {
                object obj = ResourceManager.GetObject("sigilBloodfiend", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBloodfiend_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilBloodfiend_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBroodMother {
            get {
                object obj = ResourceManager.GetObject("sigilBroodMother", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBroodMother_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilBroodMother_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBurning {
            get {
                object obj = ResourceManager.GetObject("sigilBurning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilBurning_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilBurning_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilConductor {
            get {
                object obj = ResourceManager.GetObject("sigilConductor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilConductor_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilConductor_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCopycat {
            get {
                object obj = ResourceManager.GetObject("sigilCopycat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCopycat_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilCopycat_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCorrector {
            get {
                object obj = ResourceManager.GetObject("sigilCorrector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCorrector_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilCorrector_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCourageous {
            get {
                object obj = ResourceManager.GetObject("sigilCourageous", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCourageous_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilCourageous_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCursed {
            get {
                object obj = ResourceManager.GetObject("sigilCursed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCursed_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilCursed_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCycler {
            get {
                object obj = ResourceManager.GetObject("sigilCycler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilCycler_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilCycler_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilFalseThrone {
            get {
                object obj = ResourceManager.GetObject("sigilFalseThrone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilFalseThrone_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilFalseThrone_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilFlagBearer {
            get {
                object obj = ResourceManager.GetObject("sigilFlagBearer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilFlagBearer_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilFlagBearer_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilFrostRuler {
            get {
                object obj = ResourceManager.GetObject("sigilFrostRuler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilFrostRuler_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilFrostRuler_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilFrozenHeart {
            get {
                object obj = ResourceManager.GetObject("sigilFrozenHeart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilFrozenHeart_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilFrozenHeart_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGardener {
            get {
                object obj = ResourceManager.GetObject("sigilGardener", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGardener_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilGardener_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGiftGiver {
            get {
                object obj = ResourceManager.GetObject("sigilGiftGiver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGiftGiver_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilGiftGiver_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGreedyHealing {
            get {
                object obj = ResourceManager.GetObject("sigilGreedyHealing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGreedyHealing_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilGreedyHealing_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGrinder {
            get {
                object obj = ResourceManager.GetObject("sigilGrinder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGrinder_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilGrinder_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGroupHealer {
            get {
                object obj = ResourceManager.GetObject("sigilGroupHealer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilGroupHealer_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilGroupHealer_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilHealer {
            get {
                object obj = ResourceManager.GetObject("sigilHealer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilHealer_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilHealer_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilIdol {
            get {
                object obj = ResourceManager.GetObject("sigilIdol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilIdol_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilIdol_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilMarksman {
            get {
                object obj = ResourceManager.GetObject("sigilMarksman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilMarksman_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilMarksman_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilMartyr {
            get {
                object obj = ResourceManager.GetObject("sigilMartyr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilMartyr_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilMartyr_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilNettles {
            get {
                object obj = ResourceManager.GetObject("sigilNettles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilNettles_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilNettles_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilNeutered {
            get {
                object obj = ResourceManager.GetObject("sigilNeutered", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilNeutered_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilNeutered_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilNeuteredLatch {
            get {
                object obj = ResourceManager.GetObject("sigilNeuteredLatch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilNeuteredLatch_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilNeuteredLatch_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilNihil {
            get {
                object obj = ResourceManager.GetObject("sigilNihil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilNihil_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilNihil_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilOneSided {
            get {
                object obj = ResourceManager.GetObject("sigilOneSided", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilOneSided_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilOneSided_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilPiercing {
            get {
                object obj = ResourceManager.GetObject("sigilPiercing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilPiercing_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilPiercing_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilProtector {
            get {
                object obj = ResourceManager.GetObject("sigilProtector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilProtector_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilProtector_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilPunisher {
            get {
                object obj = ResourceManager.GetObject("sigilPunisher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilPunisher_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilPunisher_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilQueenNest {
            get {
                object obj = ResourceManager.GetObject("sigilQueenNest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilQueenNest_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilQueenNest_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilQuickDraw {
            get {
                object obj = ResourceManager.GetObject("sigilQuickDraw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilQuickDraw_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilQuickDraw_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilReflector {
            get {
                object obj = ResourceManager.GetObject("sigilReflector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilReflector_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilReflector_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilRegenerator {
            get {
                object obj = ResourceManager.GetObject("sigilRegenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilRegenerator_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilRegenerator_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilReturnToNihil {
            get {
                object obj = ResourceManager.GetObject("sigilReturnToNihil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilReturnToNihil_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilReturnToNihil_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilRightfulHeir {
            get {
                object obj = ResourceManager.GetObject("sigilRightfulHeir", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilRightfulHeir_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilRightfulHeir_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilRoots {
            get {
                object obj = ResourceManager.GetObject("sigilRoots", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilRoots_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilRoots_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilScrambler {
            get {
                object obj = ResourceManager.GetObject("sigilScrambler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilScrambler_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilScrambler_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSerpentsNest {
            get {
                object obj = ResourceManager.GetObject("sigilSerpentsNest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSerpentsNest_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilSerpentsNest_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSigilPower {
            get {
                object obj = ResourceManager.GetObject("sigilSigilPower", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSigilPower_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilSigilPower_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSlime {
            get {
                object obj = ResourceManager.GetObject("sigilSlime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSlime_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilSlime_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSpores {
            get {
                object obj = ResourceManager.GetObject("sigilSpores", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSpores_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilSpores_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSporogenic {
            get {
                object obj = ResourceManager.GetObject("sigilSporogenic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilSporogenic_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilSporogenic_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilTeamLeader {
            get {
                object obj = ResourceManager.GetObject("sigilTeamLeader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilTeamLeader_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilTeamLeader_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilTheTrain {
            get {
                object obj = ResourceManager.GetObject("sigilTheTrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilTheTrain_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilTheTrain_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilThickSkin {
            get {
                object obj = ResourceManager.GetObject("sigilThickSkin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilThickSkin_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilThickSkin_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilTime {
            get {
                object obj = ResourceManager.GetObject("sigilTime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilTime_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilTime_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilVolatile {
            get {
                object obj = ResourceManager.GetObject("sigilVolatile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilVolatile_flipped {
            get {
                object obj = ResourceManager.GetObject("sigilVolatile_flipped", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilVolatile_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilVolatile_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilWitness {
            get {
                object obj = ResourceManager.GetObject("sigilWitness", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilWitness_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilWitness_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilWoodcutter {
            get {
                object obj = ResourceManager.GetObject("sigilWoodcutter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilWoodcutter_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilWoodcutter_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilYellowBrickRoad {
            get {
                object obj = ResourceManager.GetObject("sigilYellowBrickRoad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilYellowBrickRoad_pixel {
            get {
                object obj = ResourceManager.GetObject("sigilYellowBrickRoad_pixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowQueenIceBlock {
            get {
                object obj = ResourceManager.GetObject("snowQueenIceBlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowQueenIceHeart {
            get {
                object obj = ResourceManager.GetObject("snowQueenIceHeart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowQueenIceHeart_emission {
            get {
                object obj = ResourceManager.GetObject("snowQueenIceHeart_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowWhitesVine {
            get {
                object obj = ResourceManager.GetObject("snowWhitesVine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] spiderBrood {
            get {
                object obj = ResourceManager.GetObject("spiderBrood", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] spiderBrood_emission {
            get {
                object obj = ResourceManager.GetObject("spiderBrood_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] spiderling {
            get {
                object obj = ResourceManager.GetObject("spiderling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] spiderling_emission {
            get {
                object obj = ResourceManager.GetObject("spiderling_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] theLittlePrinceMinion {
            get {
                object obj = ResourceManager.GetObject("theLittlePrinceMinion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] theLittlePrinceMinion_emission {
            get {
                object obj = ResourceManager.GetObject("theLittlePrinceMinion_emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] theNakedWorm {
            get {
                object obj = ResourceManager.GetObject("theNakedWorm", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
